### ISSUE TITLE
An Error Has Occurred. Arm11.

### ISSUE THREAD

**Issue by GoFloatYourself** [zoogie/new-browserhax#3]
It seems as if every time I attempt I use the QR code and install, i immediately get an error afterwards. I’m not too sure what is wrong as I’ve made sure everything is perfect multiple times. Is this common? Any help would be appreciated. Thank you.

**Comment by zoogie** [comment]
It is common. It means you already have cfw and you don't need to use browserhax anymore. Browserhax wasn't designed to run under a cfw context, so the cfw code conflicts with it and causes browserhax to crash.

Visit this discord site for further instructions. Reference this issue when you ask for help.
https://discord.gg/C29hYvh

**Comment by zoogie** [comment]
It appears you were already there it seems. If you get no response after a few minutes, just keep asking. Those help channels can get really busy.

**Comment by GoFloatYourself** [comment]
I previously had CFW on my 2ds xl. I originally had the thought that upon removal of everything on the SD that the CFW would have been removed. I should have realized that isn’t the case. I went through the steps to remove the CFW I had and I will try to reinstall this one in the morning.

Thank you for your time.

**Comment by zoogie** [comment]
You should have left the old cfw installed, but it's too late now, you'll have to reinstall.

Seedminer, frogminer, fredtool, bannerbomb3, soundhax/safehax, ntrboot, browserhax 2020, etc., they all end up at the same point when completed, and that's B9S installed to firm. The only practical difference between them is how hard/easy they are to install. The end result is the same.
